// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    var argv, greet;
    greet = require("../lib/");
    argv = require('minimist')(process.argv.slice(2));
    console.log(greet.init(argv._, argv.drink));
  };

}).call(this);
