// Generated by CoffeeScript 1.7.1
(function() {
  var greet;

  greet = {};

  greet.init = function(name, drunk) {
    var result;
    this.name = name;
    this.drunk = drunk;
    result = this.say();
    return result;
  };

  greet.say = function() {
    if (this.name.length === 0) {
      return "what you name?";
    } else {
      if (this.drunk) {
        return "hello " + this.name + ", you look sexy today";
      } else {
        return "hello, " + this.name;
      }
    }
  };

  module.exports = greet;

}).call(this);
